version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00" # UTC
    labels:
      - "domain: deps"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 100
    groups:
      amq:
        patterns:
        - "amq-*"
      aws:
        patterns:
        - "aws-*"
      azure:
        patterns:
        - "azure_*"
      clap:
        patterns:
        - "clap*"
      csv:
        patterns:
        - "csv*"
      futures:
        patterns:
        - "futures"
        - "futures-util"
      phf:
        patterns:
        - "phf*"
      prost:
        patterns:
        - "prost"
        - "prost-*"
      tonic:
        patterns:
        - "tonic"
        - "tonic-*"
      wasm-bindgen:
        patterns:
        - "wasm-bindgen-*"
      zstd:
        patterns:
        - "zstd*"
  - package-ecosystem: "docker"
    directory: "/distribution/docker/"
    schedule:
      interval: "daily"
      time: "04:00" # UTC
    labels:
      - "domain: deps"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 100
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "domain: ci"
    commit-message:
      prefix: "chore(ci)"
