blank_issues_enabled: true

contact_links:
  - name: Support
    url: https://discussions.vector.dev
    about: Get help! Ask questions, get support, and share ideas.

  - name: Chat
    url: https://chat.vector.dev
    about: Engage with the Vector team and other community members.

  - name: Twitter
    url: https://twitter.com/vectordotdev
    about: Follow us and stay up to date with Vector.

