apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vector

resources:
  - configmap.yaml
  - deployment.yaml
  - service-headless.yaml
  - service.yaml
  - serviceaccount.yaml
