name: Protobuf Compatibility

on:
  pull_request:
    paths:
        - "proto/**"
        - "lib/vector-core/proto/**"
  merge_group:
    types: [checks_requested]

concurrency:
    # `github.event.number` exists for pull requests, otherwise fall back to SHA for merge queue
    group: ${{ github.workflow }}-${{ github.event.number || github.event.merge_group.head_sha }}
    cancel-in-progress: true

jobs:
  validate-protos:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v3
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1.27.2
      # Perform breaking change detection against the `master` branch
      - uses: bufbuild/buf-breaking-action@v1.1.3
        with:
          against: "https://github.com/vectordotdev/vector.git#branch=master"
