name: Release Suite

on:
  push:
    tags:
      - v0.*
      - v1.*

jobs:
  Release:
    uses: ./.github/workflows/publish.yml
    with:
      git_ref: ${{ github.ref }}
      channel: release
    secrets: inherit
