[package]
name = "vdev"
version = "0.1.0"
edition = "2021"
authors = ["Vector Contributors <vector@datadoghq.com>"]
license = "MPL-2.0"
readme = "README.md"
publish = false

[dependencies]
anyhow = "1.0.75"
cached = "0.46.0"
chrono = { version = "0.4.31", default-features = false, features = ["serde", "clock"] }
clap = { version = "4.4.7", features = ["derive"] }
clap-verbosity-flag = "2.1.0"
clap_complete = "4.4.4"
confy = "0.5.1"
directories = "5.0.1"
# remove this when stabilized https://doc.rust-lang.org/stable/std/path/fn.absolute.html
dunce = "1.0.4"
glob = { version = "0.3.1", default-features = false }
hex = "0.4.3"
indexmap = { version = "2.0", default-features = false, features = ["serde", "std"] }
indicatif = { version = "0.17.7", features = ["improved_unicode"] }
itertools = "0.11.0"
log = "0.4.20"
once_cell = "1.18"
os_info = { version = "3.7.0", default-features = false }
# watch https://github.com/epage/anstyle for official interop with Clap
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
paste = "1.0.14"
regex = { version = "1.10.2", default-features = false, features = ["std", "perf"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.27"
sha2 = "0.10.8"
tempfile = "3.8.1"
toml = { version = "0.8.6", default-features = false, features = ["parse"] }
